### ISSUE TITLE
"README.md"の誤字について

### ISSUE THREAD

**Issue by ghost** [manju-summoner/ManjuSummonerMiniTools#1]
### "README.md"の誤字について

こんにちは、いつもYMM4やゆっくリサンプラーを使っているものです

こちらの[https://github.com/manju-summoner/ManjuSummonerMiniTools](ツール置き場)のREADME.md

> FireAlpaka 等で利用可能。

が誤字で正規表現は
> FireAlpaca 等で利用可能。

が正規表現となります

@manju-summoner 
修正お願いいたします

**Comment by manju-summoner** [comment]
修正しました！ありがとうございます！

**Comment by ghost** [comment]
対応いただきありがとうございました！
